### ISSUE TITLE
Does it support static linking and musl?

### ISSUE THREAD

**Issue by tufeigunchu** [dmitriy-philimonov/elfremapper#1]
It will be interesting to use in static linking  elf with musl

**Comment by dmitriy-philimonov** [comment]
Regarding static linking. The short answer is "NO". The long answer is given in my article [here](https://mysqlperf.github.io/mysql/elfremapper/), i.e. the first version of `elfremapper` was statically linked code based on the `hugetlbfs` and `MAP_SHARED` pages and it had some problems with `gdb`/`fork`, so I wouldn't recommend this approach. However, If you're still interested and ready to undertake possible negative consequences, feel free to use the `elfremapper::v1` which was originally published as a patch for MariaDB [here](https://jira.mariadb.org/browse/MDEV-24051).

Regarding `musl` library. It wasn't tested, although I believe it should work, because there's nothing `glibc`-specific under the hood. I'd recommend to test it this way:
* prepare your default release application build with `musl`
* compile `elfremapper` with `-DMAKE_LD_PRELOAD_LIBRARY=1`
* Run LD_PRELOAD=./libelfremapper.so ./your-application

**Comment by tufeigunchu** [comment]
Yes it works with normal way.  I still not sure if shared libraries (such as libc.so.6 libstdc++.so.6)being moved to hugepages or not.
Another topic is about static linking. There is a tool https://github.com/upx/upx. It did similar way to map segments of target application and execute it. It supports static link application. If we change upx code to let it remap with hugepages, will it support static linking now?

**Comment by tufeigunchu** [comment]
I found another one https://github.com/MikhailProg/elf and it meets my purpose.
