### ISSUE TITLE
hugepage=1G

### ISSUE THREAD

**Issue by Young-xin** [dmitriy-philimonov/elfremapper#3]
hi！my program used hugepage=1G，I have tried using libhugetlbfs，But it didn't work。How can I map BSS、DATA、TEXT to hugepage=1G？

**Comment by dmitriy-philimonov** [comment]
I guess you can have a try: the changes in the code are very limited:

1. change HUGE_PAGE_SIZE specified in hex:
```cpp
#define HUGE_PAGE_SIZE 0x40000000
```
2. change MAP_HUGE_2MB to MAP_HUGE_1GB
```cpp
#ifndef MAP_HUGE_1GB
#define MAP_HUGE_1GB (30 << MAP_HUGE_SHIFT)
#endif
```
3. change all occurrences of MAP_HUGE_2MB to MAP_HUGE_1GB
4. **Do not** compile with -zcommon-page-size and -zmax-page-size, otherwise the memory waste is going to be extremely huge

However, be aware, that you should:
1. Allocate at least one page with size 1GB
2. The whole page will be consumed by the TEXT + DATA + BSS segment of your binary.

**Pay attention**

I personally can't image that you have a binary with 1GB code/data segment (BSS+DATA+TEXT). Run readelf:
```shell
$ readelf -Wl $your_binary
```

Look at Type=LOAD segments to FileSiz column. I guess, you will see several orders of magnitude much smaller values. Only LOAD sections are loaded during application execution.

Otherwise, you might brought a huge peace of constant data into DATA segment, or allocate a huge buffer in BSS. In that case, I assume, you can achieve better results if you just `mmap` the 1GB huge page at startup.

**Comment by Young-xin** [comment]
thanks very much ！I'm trying to enable both 1G hugepage and 2M hugepage  and attempting to map data、text、bss to 2M hugepage with libhugetlbfs.

**Comment by dmitriy-philimonov** [comment]
1G pages for code will not be supported. It's over the top feature for any feasible binary today.
